name: Doker Image CI
on:
  push:
    branches: [main,dev]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@2
      - name: Doker Login
        env: 
          DOKER_USER: ${{secrets.DOCKER_USER}}
          DOKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOKER_USER -p $DOCKER_PASSWORD
      - name: Build Doker Image
        run: docker built . --file dockerfile.dev -t robertnch03/starter:$(date +%s)
      - name: Push Docker Image to Dockerhub
        run: docker push $DOKER_USER/starter