name: unit-tests
on:
  push:
    branches: [main,dev]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - user: actions/checkout@2
    - name: Use Node-js 14.x
      uses: actions/setup-node@v1
      with: 
        node-version: 14.x
    - run: npm ci
    - run: npm test